# Generated by Django 6.1 on 2026-08-12 17:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometría')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Geometría de prueba',
                'verbose_name_plural': 'Geometrías de prueba',
            },
        ),
    ]
